baseurl = "http://prokopto.dev"
title = "Courtney Caldwell"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

[services]
[services.disqus]
disqusShortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "Courtney Caldwell"
  info = "(Currently) Independent Researcher and Software Engineer"
  description = "Courtney Caldwell's personal website/blog!"
  keywords = "blog,developer,personal,philosophy,science,computerscience,compsci"
  avatarurl = "static/images/qrface.jpg"
  #gravatar = "john.doe@example.com"

  # faviconSVG = "static/images/qrface.jpg"
  favicon_32 = "static/icons8-code-office-xs-32.png"
  favicon_16 = "static/icons8-code-office-xs-16.png"

  since = 2023

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/prokopto-dev/"
[[params.social]]
  name = "Mastodon"
  icon = "fa-brands fa-mastodon fa-2x"
  weight = 2
  url = "https://mastodon.social/@prokoptodev"
[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 3
  url = "https://linkedin.com/in/courtney-ccc/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"

[[menu.main]]
  name = "QR-Face"
  weight = 3
  url = "qr-face/"
